# Generated by Django 6.0.7 on 2026-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('poster_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-release_year', 'title'],
            },
        ),
    ]
